export enum JobApplicationStatus {
    APPLIED = 'APPLIED',
    INTERVIEW_1 = 'INTERVIEW_1',
    INTERVIEW_2 = 'INTERVIEW_2',
    INTERVIEW_3 = 'INTERVIEW_3',
    TECHNICAL_TASK_1 = 'TECHNICAL_TASK_1',
    TECHNICAL_TASK_2 = 'TECHNICAL_TASK_2',
    OFFER = 'OFFER',
    REJECTED = 'REJECTED',
    ARCHIVED = 'ARCHIVED',
}
